config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  root "recipes#index"

  # Optional routes for health check and PWA
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, :ingredients, :instructions, presence: true
  belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_recipe, only: [ :show, :edit, :update, :destroy ]
  def index
    @recipes = if params[:search]
      Recipe.where("title LIKE ?", "%#{params[:search]}%")
    else
     Recipe.all
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to(@recipe, notice: "Recipe was successfully created!")
    else
      render(:new)
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recipe was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: "Recipe was successfully deleted!"
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, :instructions, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ryori Gram" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= form_with(model: @recipe, local: true) do |form| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :ingredients%>
    <%= form.text_area :ingredients%>
  </div>

  <div>
    <%= form.label :instructions%>
    <%= form.text_area :instructions%>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="header">
  <h1>りょうり グラム🦞</h1>
  <div class="navigation-bar">
    <nav>
      <% if user_signed_in? %>
        <div class="user-details">
          Logged in as (<%= current_user.email %>)
          <%= button_to"Sign Out", destroy_user_session_path, method: :delete %>
        </div>
      <% else %>
        <a class="sign" href="/users/sign_in">Sign in</a>
      <% end %>
    </nav>


  </div>

  <p></p>

  <%= form_with(url: recipes_path, method: :get, local: true) do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search recipes" %>
    <%= submit_tag "Search" %>
  <% end %>

  <p></p>
  <%= link_to 'New Recipe', new_recipe_path %>

  <ol>
    <% @recipes.each do |recipe| %>
      <li>
        <%= link_to recipe.title, recipe_path(recipe) %> by <%= recipe.user.email %> 
      </li>
    <% end %>
  </ol>

  <footer class="footer">
    <p>© 2024 Ryori Gram.</p>
  </footer>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= form_with(model: @recipe, local: true) do |form| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :ingredients%>
    <%= form.text_area :ingredients%>
  </div>

  <div>
    <%= form.label :instructions%>
    <%= form.text_area :instructions%>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<%= image_tag(@recipe.image) if @recipe.image.attached? %>
<h4>Ingredients: <%= @recipe.ingredients%></h4>
<p>Directions: <%= @recipe.instructions%></p>

<% if @recipe.user == current_user %>
  <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
  <%= link_to 'Delete', @recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>